---
- name: Temporarily enable passwordless sudo for the ansible_user
  lineinfile:
    dest: /etc/sudoers
    regexp: '^{{ homebrew_install_user }}'
    line: '{{ homebrew_install_user }} ALL=(ALL) NOPASSWD: ALL'
    state: present
    validate: 'visudo -cf %s'
    mode: 0644
  when: homebrew_temporary_passwordless_sudo

- name: Install Homebrew if not already installed
  include_tasks: install-Darwin.yml

- name: Re-enable sudo with password
  lineinfile:
    dest: /etc/sudoers
    regexp: '^{{ homebrew_install_user }}'
    line: '{{ homebrew_install_user }} ALL=(ALL) ALL'
    state: present
    validate: 'visudo -cf %s'
    mode: 0644
  when: homebrew_temporary_passwordless_sudo
